--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/Arzxy/Unregister-Cmd
build-by-default: true
branches:
- master
projects:
  Unregister-Cmd:
    path: ""
    icon: "assets/icon.png"
...
